# Use an official Python runtime as a parent image.
FROM python:3.12-slim

# Set the working directory to /app.
WORKDIR /app

# Copy requirements file into the container at /app.
COPY requirements.txt .

# Install any needed packages specified in requirements.txt.
RUN pip install --upgrade pip && pip install -r requirements.txt

# Download necessary NLTK resources.
RUN python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords'); nltk.download('wordnet')"

# Copy the rest of the application files to the container.
COPY . .

# Expose port 8080 to the outside world.
EXPOSE 8080

# Define environment variable for Flask (if required)
ENV FLASK_APP=deploy.py

# Run deploy.py when the container launches.
CMD ["python", "deploy.py"]
